language: android
sudo: false

addons:
  apt:
    packages:
      - lib32z1


android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository


before_install:
  # newest Android NDK
  - wget https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip -O ndk.zip
  - unzip -q ndk.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r15c
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}

script:
  - chmod +x gradlew
  - ./gradlew build