language: android
sudo: false

addons:
  apt:
    packages:
      - lib32z1


android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository


before_install:
  # https://stackoverflow.com/questions/47719282/i-cant-build-android-27-tool-27-0-2-with-travis-ci/47726910#47726910
  - yes | sdkmanager "platforms;android-27"
  # newest Android NDK
  - wget https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip -O ndk.zip
  - unzip -q ndk.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r15c
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}

script:
  - chmod +x gradlew
  - ./gradlew build