language: android
sudo: false

addons:
  apt:
    packages:
      - libgd2-xpm
      - ia32-libs
      - ia32-libs-multiarch


android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository


before_install:
  # newest Android NDK
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86.bin -O ndk.bin; fi
  - chmod +x ndk.bin
  - ./ndk.bin > /dev/null
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
  # manually set sdk.dir variable, according to local paths
  #- echo "sdk.dir=$ANDROID_HOME" > local.properties
  #- echo yes | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-21,build-tools-19.1.0 --force --no-ui
  - cd ${TRAVIS_BUILD_DIR}/App
  - ndk-build -j
